import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import logging
from typing import List, Optional, Tuple
from models.dto import WLEDDeviceDTO
from services.settings_service import get_setting
from db.sqlite import get_all_wled_devices

logger = logging.getLogger(__name__)

class EmailService:
    def __init__(self):
        pass

    def _get_smtp_config(self):
        """Retrieve SMTP configuration from settings."""
        return {
            "host": get_setting("smtp_host"),
            "port": int(get_setting("smtp_port") or 587),
            "user": get_setting("smtp_user"),
            "password": get_setting("smtp_password"),
            "sender": get_setting("smtp_sender"),
            "receiver": get_setting("smtp_receiver"),
        }

    def generate_backup_html(self, devices: List[WLEDDeviceDTO]) -> str:
        """Generate HTML content for the backup email."""
        
        rows = ""
        for device in devices:
            # Get full device info to access the actual mDNS name from config
            from db.sqlite import get_latest_device_info
            
            name = device.name or device.local_name or device.mac
            ip = device.last_ip
            
            # Initialize variables to avoid UnboundLocalError
            full_info = None
            cfg = {}
            
            # Default to hostname (basic .local)
            mdns_name = device.hostname
            
            # Try to get the actual configured mDNS name
            try:
                full_info = get_latest_device_info(device.mac)
                if full_info and 'cfg' in full_info:
                    cfg = full_info['cfg']
                    if 'id' in cfg and 'mdns' in cfg['id'] and cfg['id']['mdns']:
                        mdns_name = cfg['id']['mdns']
                        logger.info(f"Device {device.mac}: Found configured mDNS name '{mdns_name}'")
                    else:
                         logger.info(f"Device {device.mac}: No custom mDNS in config, using defaults")
                else:
                     logger.info(f"Device {device.mac}: No config found, using hostname '{device.hostname}'")
            except Exception as e:
                logger.error(f"Error fetching detailed config for device {device.mac}: {e}")
            
            # Explicitly log the final decision for LDKWLEDBulbBlack to debug user report
            ip_link = f'<a href="http://{ip}">{ip}</a>' if ip else "N/A"
            local_link = f'<a href="http://{mdns_name}.local">{mdns_name}.local</a>' if mdns_name else "N/A"
            
            rows += f"""
            <tr>
                <td style="padding: 8px; border: 1px solid #ddd;">{name}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">{ip_link}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">{local_link}</td>
            </tr>
            """

        html = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; }}
                table {{ border-collapse: collapse; width: 100%; }}
                th, td {{ text-align: left; padding: 8px; }}
                tr:nth-child(even) {{ background-color: #f2f2f2; }}
                th {{ background-color: #4CAF50; color: white; }}
            </style>
        </head>
        <body>
            <h2>WLED Devices Backup Access</h2>
            <p>Here is the list of your WLED devices. You can use these links to access them directly if the manager is down.</p>
            <table>
                <tr>
                    <th>Device Name</th>
                    <th>IP Address</th>
                    <th>mDNS (.local)</th>
                </tr>
                {rows}
            </table>
            <p>Generated by WLED Manager</p>
        </body>
        </html>
        """
        return html

    def send_email(self, subject: str, html_content: str) -> Tuple[bool, Optional[str]]:
        """
        Send an email with the given subject and HTML content.
        Returns: (success, error_message)
        """
        config = self._get_smtp_config()
        
        # Sanitize config to remove non-breaking spaces
        for key in ["host", "user", "password", "sender", "receiver"]:
            if isinstance(config.get(key), str):
                config[key] = config[key].strip().replace('\xa0', '')
        
        if not all([config["host"], config["user"], config["password"], config["sender"], config["receiver"]]):
            msg = "SMTP configuration is incomplete. Please check settings."
            logger.error(msg)
            return False, msg

        try:
            from email.header import Header
            
            msg = MIMEMultipart("alternative")
            msg["Subject"] = Header(subject, 'utf-8')
            msg["From"] = config["sender"]
            msg["To"] = config["receiver"]

            part = MIMEText(html_content, "html", "utf-8")
            msg.attach(part)

            with smtplib.SMTP(config["host"], config["port"]) as server:
                server.starttls()
                server.login(config["user"], config["password"])
                server.sendmail(config["sender"], config["receiver"], msg.as_string())
            
            logger.info(f"Email sent successfully to {config['receiver']}")
            return True, None
        except Exception as e:
            error_msg = f"Failed to send email: {str(e)}"
            logger.error(error_msg)
            return False, str(e)

    def send_backup_email(self) -> Tuple[bool, Optional[str]]:
        """Fetch devices, generate HTML, and send backup email."""
        try:
            devices_models = get_all_wled_devices()
            devices = [WLEDDeviceDTO(**d.dict()) for d in devices_models]
            
            if not devices:
                logger.warning("No devices found to backup.")
                return False, "No devices found to backup."

            html_content = self.generate_backup_html(devices)
            return self.send_email("WLED Devices Backup Access", html_content)
        except Exception as e:
            error_msg = f"Error in send_backup_email: {e}"
            logger.error(error_msg)
            return False, str(e)
