apiVersion: v1
kind: Service
metadata:
  name: wled-manager-backend
  namespace: wled
  labels:
    app: wled-manager
    tier: backend
spec:
  selector:
    app: wled-manager
    tier: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
