apiVersion: v1
kind: Secret
metadata:
  name: wled-manager-backend-secret
  namespace: wled
type: Opaque
stringData:
  # CHANGE THIS! Generate with: openssl rand -base64 32
  SECRET: "CHANGE-THIS-TO-A-RANDOM-SECRET-KEY"
