apiVersion: v1
kind: Service
metadata:
  name: wled-manager-frontend
  namespace: wled
  labels:
    app: wled-manager
    tier: frontend
spec:
  selector:
    app: wled-manager
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
